language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - nosetests --with-coverage --cover-package=CodebenderTest
    - flake8 setup.py CodebenderTest tests
after_success:
  - coveralls